apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: r53spflat
  description: Compact large SPF chains into flat blocks of IP addresses
  annotations:
    ## Path to mkdocs.yml that is relative to the source of the catalog-info.yaml
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Staffbase/r53spflat
  tags:
    - infrastructure
    - mail
    - python
    - security
    - spf
spec:
  type: service
  lifecycle: production
