[metadata]
name=r53spflat
version=22.02.20
author = weizenspreu
author_email = kevin.niehage@staffbase.com
description = Flattens SPF records and updates Cloudflare zones
long_description = file: README.md
long_description_content_type = text/markdown
license_files = LICENSE.txt
url = https://github.com/Staffbase/r53spflat
project_urls =
    repo = https://github.com/Staffbase/r53spflat.git
    overview = https://github.com/Staffbase/r53spflat/blob/main/README.md
classifiers = 
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
keywords='route53 aws dns spf flattener'
[options]
include_package_data = True
package_dir = 
    = src
packages = find:
install_requires =
    boto3>=1.21.3
    sender-policy-flattener @ https://github.com/staffbase/sender_policy_flattener/archive/b9f0658573ca906a493d012fe8138e4ebd1c0fed.tar.gz
python_requires = >=3.6
scripts = 
    scripts/r53spflat
[options.data_files] 
[options.packages.find]
where = src
